"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../controllers/auth");
const getme_1 = require("../middleware/getme");
const router = (0, express_1.Router)();
router.post("/signup", auth_1.signup);
router.post("/login", auth_1.login);
router.post("/logout", auth_1.logout);
router.get("/me", getme_1.verifyToken, auth_1.getMe);
router.put("/userEdit", getme_1.verifyToken, auth_1.updateMe);
exports.default = router;
