"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const properties_1 = require("../controllers/properties");
const verifyRole_1 = require("../middleware/verifyRole");
const router = (0, express_1.Router)();
router.post("/createproperty", (0, verifyRole_1.verifyRole)(["owner"]), properties_1.createProperty);
router.get("/allproperty", properties_1.properties);
router.get("/:id", properties_1.propertyId);
exports.default = router;
